### PR TITLE
Make inventory WUAUpdates call spawn a new process, retry on metadata unmarshal error

### LINKED ISSUE #154: OSConfig Agent "unexpected end of JSON input"
I have a VM instance running Debian GNU/Linux 9 (stretch), it has the OSConfig Agent installed and running.  I have encountered the following error several times. 

```
 {
  "insertId": "ezj5okfzvhagf",
  "jsonPayload": {
    "localTimestamp": "2020-03-03T18:37:28.4900Z",
    "message": "unexpected end of JSON input"
  },
  "resource": {
    "type": "gce_instance",
    "labels": {
      "instance_id": "<INSTANCE_ID>",
      "zone": "us-central1-a",
      "project_id": "<PROJECT_ID>"
    }
  },
  "timestamp": "2020-03-03T18:37:28.737755265Z",
  "severity": "ERROR",
  "logName": "projects/<PROJECT_ID>/logs/OSConfigAgent",
  "sourceLocation": {
    "file": "main.go",
    "line": "154",
    "function": "main.runLoop"
  },
  "receiveTimestamp": "2020-03-03T18:37:30.853440003Z"
}
```
I have installed nodejs 12.16.1.

### PR DESCRIPTION
**Pull request by adjackura**
We have issues with the WUA api leaking memory, this is an issue with the inventory calls because they run so often.  To solve this the list calls for inventory spawn a new instance of the agent to query the api, this is only implemented for inventory calls as patch calls do not run that often before an agent restart and the miniscule memory buildup per run will never be noticed.

Make sure we close clients when done with them.

The metadata unmarshal sometimes returns an error, this most often will be because of a bad send from the metadata server and can just be retried safely to avoid logging this error. (fixes #154)

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -258,6 +259,15 @@ func main() {
 	}
 
 	switch action := flag.Arg(0); action {
+	// wuaupdates just runs the packages.WUAUpdates function and returns it's output
+	// as JSON on stdout. This avoids memmory issues with the WUA api since this is
```
Comment (wj-chen) [inline main.go:263]: "memory"

File: packages/packages_windows.go [hunk 2]
```diff
@@ -15,17 +15,40 @@ package packages
...
 	"fmt"
+	"os"
+	"os/exec"
 	"strings"
 
 	"github.com/GoogleCloudPlatform/osconfig/clog"
 	"github.com/GoogleCloudPlatform/osconfig/util"
 )
 
+// In order to work around memmory issues with the WUA library we spawn a
```
Comment (wj-chen) [inline packages/packages_windows.go:29]: "memory"

**Review by wj-chen — COMMENTED** [review]
LGTM
